# Generated by Django 2.2.5 on 2020-04-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_token_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32, null=True)),
                ('pwd', models.CharField(max_length=32)),
                ('re_pwd', models.CharField(max_length=32)),
                ('phone_num', models.IntegerField(max_length=11)),
                ('mail', models.CharField(max_length=32)),
            ],
        ),
    ]
