# Generated by Django 2.2.5 on 2020-04-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phone_num',
            field=models.IntegerField(max_length=40),
        ),
    ]
