# Generated by Django 2.2.5 on 2020-04-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20200403_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phone_num',
            field=models.CharField(max_length=100),
        ),
    ]
