# Generated by Django 2.2.5 on 2020-04-03 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20200403_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='re_pwd',
        ),
    ]
